    - name: Pull Docker image
      docker_image:
        name: ahmedmobarak1994/team-basis-labs:latest
        source: pull
    - name: Start Docker container
      docker_container:
        name: my_container
        image: ahmedmobarak1994/team-basis-labs:latest
        state: started
        ports:
          - 80:80
